# Netflix Dataset analysis
<h2><b>Task-1</b> Netflix Data Cleaning & Preparation</h2>
<h3><b>Description :</b> Prepare and organize the Netflix dataset for business analytics and
reporting. </h3>
<h4><b>Step 1:</b> Import the dataset using Python and Pandas.</h4>

In [10]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv("Dataset.csv")
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

<h5><b>Imported 2 libraries:-</b> <br>Numpy for numerical operations.<br>Pandas for high efficiency computation.</h5>

In [11]:
df.shape

(8790, 10)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 1.6 MB

<h4><b>Step 2:</b> Identify and handle missing values.<br>
<b>Step 3:</b> Remove duplicate records and formatting
inconsistencies.<br>
<b>Step 4:</b> Standardize columns such as Country, Rating, and
Type.
</h4>

In [13]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

<h5>So there we did'nt find any missing values or null values</h5>

In [16]:
df.shape

(8790, 10)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 1.6 MB

In [18]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [22]:
cat_cols = df.select_dtypes(include='object').columns
cat_cols

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'rating', 'duration', 'listed_in'],
      dtype='str')

In [25]:
for col in cat_cols:
    print(f"\n{'='*20}")
    print(col)
    print(df[col].nunique())

====================
show_id
8790

====================
type
2

====================
title
8787

====================
director
4528

====================
country
86

====================
date_added
1713

====================
rating
14

====================
duration
220

====================
listed_in
513

In [26]:
cols = ['type', 'country', 'rating']
# i take it because they gives very low cardinality so we can check or handle the incosistency.
for col in cols:
    print(f"\n===== {col} =====")
    print(sorted(df[col].unique()))

===== type =====
['Movie', 'TV Show']

===== country =====
['Argentina', 'Australia', 'Austria', 'Bangladesh', 'Belarus', 'Belgium', 'Brazil', 'Bulgaria', 'Cambodia', 'Cameroon', 'Canada', 'Chile', 'China', 'Colombia', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Egypt', 'Finland', 'France', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Kuwait', 'Lebanon', 'Luxembourg', 'Malaysia', 'Mauritius', 'Mexico', 'Mozambique', 'Namibia', 'Netherlands', 'New Zealand', 'Nigeria', 'Norway', 'Not Given', 'Pakistan', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Romania', 'Russia', 'Saudi Arabia', 'Senegal', 'Serbia', 'Singapore', 'Slovenia', 'Somalia', 'South Africa', 'South Korea', 'Soviet Union', 'Spain', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Thailand', 'Turkey', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Venezuela', 'Vietnam', 'West Germany', 'Zimbabwe']

===== rating =====
['G', 'NC-17', 'NR', 'PG', 'PG-13', 'R', 'TV-14', 'TV-G', 'TV-MA', 'TV-PG', 'TV-Y', 'TV-Y7', 'TV-Y7-FV', 'UR']

In [28]:
df['country'].value_counts().head(10)

country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
Canada             271
Japan              259
South Korea        214
France             213
Spain              182
Name: count, dtype: int64

In [71]:
df['country'] = df['country'].str.strip().str.title()

In [72]:
df[df['country'] == 'Not Given']['title'].duplicated().sum()

np.int64(0)

In [73]:
df['country'] = df['country'].replace('Not Given', 'Unknown')

<h5> i replaced the Not Given feature to Unknown because we can't actually decide the country of the data set because,
    it is a categorical column and we cannot decide the exact country for the movie so we will replace it with Unknown</h5>

In [45]:
temp = df.groupby('title')['director'].unique().reset_index(name='directors')
temp['directors']

0                            [Cho Il]
1       [Sabina Fedeli, Anna Migotto]
2                     [Rako Prijanto]
3                     [Rako Prijanto]
4                   [Michael Kennedy]
                    ...
8782                        [Unknown]
8783                        [Unknown]
8784                        [Unknown]
8785                  [Hong-seon Kim]
8786                  [Young Jun Lee]
Name: directors, Length: 8787, dtype: object

<h5>Hypothesis 1:<br>
we cannot fill the director by same title? -- No</h5>

In [46]:
possible_fill = temp[temp['directors'].apply(lambda x: ('Not Given' in x) and (len(set(x) - {'Not Given'}) > 0))]
print("Titles that can be safely filled :", len(possible_fill))

Titles that can be safely filled : 0

<h5>The possibility of recovering missing <b>director names</b> using duplicate movie titles was investigated. No matching titles with valid director information were found. Therefore, the missing director values cannot be reliably inferred from the existing dataset.</h5>

In [47]:
df['director'] = df['director'].replace('Not Given', 'Unknown')

<h5> i replaced the Not Given feature to Unknown because we can't actually decide the director as well of the data set because,
    it is also a kind of categorical column and we cannot decide the exact Director name for the movie so we will replace it with Unknown</h5>

In [57]:
df['duration'].str.extract(r'([A-Za-z ]+)$')[0].value_counts()
#str.extract(r'([A-Za-z ]+)$')[0] -- used to count the total frequency of the "min","Season","Seasons" feature.

0
min        6126
Season     1791
Seasons     873
Name: count, dtype: int64

In [51]:
df[(df['type']=='Movie') &(df['duration'].str.contains('Season', case=False))]

Empty DataFrame
Columns: [show_id, type, title, director, country, date_added, release_year, rating, duration, listed_in]
Index: []

<h5>It checks the Seasons must not appear in Movies because movies does not contain seasons</h5>

In [60]:
df[(df['type'] =='TV Show')& (df['duration'].str.contains('min', case=False))]

Empty DataFrame
Columns: [show_id, type, title, director, country, date_added, release_year, rating, duration, listed_in]
Index: []

<h5>It checks the Minutes must not appear in TV shows because tv shows does not contain minutes</h5>

In [61]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [62]:
df['date_added'].dtype

In [63]:
df['date_added'].head(10)

0    9/25/2021
1    9/24/2021
2    9/24/2021
3    9/22/2021
4    9/24/2021
5    9/24/2021
6    9/24/2021
7     5/1/2021
8    9/23/2021
9     5/1/2021
Name: date_added, dtype: str

In [64]:
df['date_added'].str.contains(r'^\d{1,2}/\d{1,2}/\d{4}$').value_counts()

date_added
True    8790
Name: count, dtype: int64

In [65]:
df['date_added'] = pd.to_datetime(df['date_added'])

In [70]:
genres = (df['listed_in'].str.split(',').explode().str.strip().sort_values().unique())
genres

<ArrowStringArray>
[          'Action & Adventure',               'Anime Features',
                 'Anime Series',             'British TV Shows',
     'Children & Family Movies',            'Classic & Cult TV',
               'Classic Movies',                     'Comedies',
               'Crime TV Shows',                  'Cult Movies',
                'Documentaries',                   'Docuseries',
                       'Dramas',         'Faith & Spirituality',
                'Horror Movies',           'Independent Movies',
         'International Movies',       'International TV Shows',
                     'Kids' TV',              'Korean TV Shows',
                 'LGBTQ Movies',                       'Movies',
             'Music & Musicals',                   'Reality TV',
              'Romantic Movies',            'Romantic TV Shows',
             'Sci-Fi & Fantasy',          'Science & Nature TV',
    'Spanish-Language TV Shows',                'Sports Movies',
              'Stand-Up Comedy', 'Stand-Up Comedy & Talk Shows',
        'TV Action & Adventure',                  'TV Comedies',
                    'TV Dramas',                    'TV Horror',
                 'TV Mysteries',          'TV Sci-Fi & Fantasy',
                     'TV Shows',                 'TV Thrillers',
                'Teen TV Shows',                    'Thrillers']
Length: 42, dtype: str

<h5>The listed_in column contains multiple genres separated by commas. The values were inspected for missing data, placeholder values, formatting issues, duplicate genres within a record, and inconsistent genre labels. No inconsistencies were found; therefore, no cleaning was required.</h5>

In [74]:
print("Dataset Shape :", df.shape)

Dataset Shape : (8790, 10)

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   datetime64[us]
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: datetime64[us](1), int64(1), str(8)
memory usage: 1.5 MB

In [77]:
df_cleaned = df.copy()
df_cleaned.to_csv("Netflix_Cleaned_Dataset.csv", index=False)